desafio/config/routes.rb
Rails.application.routes.draw do
  
  resources :clientes

  get '/clientes/busca/:nome' , :controller => 'clientes', :action => 'shownome'

  root 'clientes#index'
end

desafio/app/models/cliente.rb
class Cliente < ActiveRecord::Base

	#busca rapida
	def self.buscarapida(args)
		if args
			where("nome LIKE '%#{args}%'")
		end 
	end

	#validacao datanascimento no cadastro
	validates :datanascimento, :mask => "99/99/9999"

end

desafio/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

desafio/app/controllers/clientes_controller.rb
class ClientesController < ApplicationController

  def index
  	@clientes = Cliente.all
  end

  def shownome
    @nomeDigitado = params[:nome]
    @clientes = Cliente.buscarapida(@nomeDigitado)
  end

  def show
    @cliente = Cliente.find(params[:id])
  end

  def new
  	@cliente = Cliente.new
  end

  def create
  	@cliente = Cliente.new(cliente_params)
    if @cliente.save
      redirect_to root_path, :notice => "Cliente registrado com sucesso!"
    else
      render "new"
    end
  end

  def edit
  	@cliente = Cliente.find(params[:id])
  end

  def update
  	@cliente = Cliente.find(params[:id])
    if @cliente.update_attributes(cliente_params)
      redirect_to root_path, :notice => "Cliente atualizado com sucesso!"
    else
      render "edit"
    end
  end

  def destroy
  	@cliente = Cliente.find(params[:id])
    @cliente.destroy
    redirect_to root_path, :notice => "Cliente excluido do sistema com sucesso!"
  end

  def cliente_params
  	allow = [:nome, :email, :datanascimento]
  	params.require(:cliente).permit(allow)
  end
  
end

desafio/app/helpers/application_helper.rb
module ApplicationHelper
end

desafio/app/helpers/cliente_helper.rb
module ClienteHelper
end

desafio/app/views/clientes/edit.html.erb
<h2>Atualizar</h2>
<%= form_for @cliente do |f| %>
	<fieldset>
	<legend>Formulario</legend>
	<% if @cliente.errors.any? %>
		<% @cliente.errors.full_messages.each do |message| %>
			<div class="alert alert-danger" role="alert">
			    <a href="javascript:;" class="alert-link"><%=message%></a>
			  </div>
		<% end %>
	<% end %>
	<div class="form-group">
		<div><%= f.label :nome %></div>
		<div><%= f.text_field :nome, :required => "true" %></div>
	</div>
	<div class="form-group">
		<div><%= f.label :email %></div>
		<div><%= f.email_field :email, :required => "true" %></div>
	</div>
	<div class="form-group">
		<div><%= f.label :datanascimento %></div>
		<div>
			<%= f.date_field :datanascimento,
				:required => "true", 
				:placeholder =>"DD/MM/AAAA",
				:value => @cliente.try(:datanascimento).try(:strftime,'%d/%m/%Y') %>
		</div>
	</div>
	<div><%= f.submit "Atualizar", :class => "btn btn-primary" %></div>
	</fieldset>
<% end %>

desafio/app/views/clientes/index.html.erb
<h2>Clientes</h2>
<% flash.each do |key,value| %>
   <div class="alert alert-success" role="alert">
    <a href="javascript:;" class="alert-link"><%=value%></a>
  </div>
<% end %>
<table class="table table-hover">
  <thead>
    <tr>
      <th>ID</th>
      <th>Nome</th>
      <th>E-mail</th>
      <th>Nascimento</th>
      <th>Opç&otilde;es</th>
    </tr>
  </thead>
  <tbody>
    <% @clientes.each do |cli| %>
    <tr>
      <td><%=cli.id%></td>
      <td><%=cli.nome%></td>
      <td><%=cli.email%></td>
      <td><%=cli.datanascimento.strftime("%d/%m/%Y")%></td>
      <td>

        <%=
          link_to "", 
          edit_cliente_path(cli), 
          :class=>"btn btn-primary glyphicon glyphicon-pencil"
        %>
       
        <%=
          link_to "", 
          cli, 
          :class=>"btn btn-primary glyphicon glyphicon-remove", 
          :data=>{:confirm =>"Voce tem certeza?"}, 
          :method => :delete 
        %>
       
      </td>
    </tr>
    <% end %>
  </tbody>
</table> 
 <p><%= link_to "Novo cadastro", new_cliente_path, :class => "btn btn-primary" %></p>







  	

desafio/app/views/clientes/new.html.erb
<h2>Cadastro</h2>
<%= form_for @cliente do |f| %>
	<fieldset>
	<legend>Formulario de cadastro</legend>
	<% if @cliente.errors.any? %>
		<% @cliente.errors.full_messages.each do |message| %>
			<div class="alert alert-danger" role="alert">
			    <a href="javascript:;" class="alert-link"><%=message%></a>
			  </div>
		<% end %>
	<% end %>
	<div class="form-group">
		<div><%= f.label :nome %></div>
		<div><%= f.text_field :nome, :required => "true" %></div>
	</div>
	<div class="form-group">
		<div><%= f.label :email %></div>
		<div><%= f.email_field :email, :required => "true" %></div>
	</div>
	<div class="form-group">
		<div><%= f.label :datanascimento %></div>
		<div>
			<%= f.date_field :datanascimento,
				:required => "true", 
				:placeholder=>"DD/MM/AAAA" %>
		</div>
	</div>
	<div><%= f.submit "Salvar", :class => "btn btn-primary" %></div>
	</fieldset>
<% end %>

desafio/app/views/clientes/show.html.erb
<h2><%= @cliente.nome %></h2>
<h2><%= @cliente.email %></h2>
<h2><%= @cliente.datanascimento %></h2>

desafio/app/views/clientes/shownome.html.erb
<h2>Busca r&aacute;pida: "<%=@nomeDigitado%>"</h2>
<table class="table table-hover">
  <thead>
    <tr>
      <th>ID</th>
      <th>Nome</th>
      <th>E-mail</th>
      <th>Nascimento</th>
      <th>Opç&otilde;es</th>
    </tr>
  </thead>
  <tbody>
    <% @clientes.each do |cli| %>
    <tr>
      <td><%=cli.id%></td>
      <td><%=cli.nome%></td>
      <td><%=cli.email%></td>
      <td><%=cli.datanascimento.strftime("%d/%m/%Y")%></td>
      <td>

        <%=
          link_to "", 
          edit_cliente_path(cli), 
          :class=>"btn btn-primary glyphicon glyphicon-pencil"
        %>
       
        <%=
          link_to "", 
          cli, 
          :class=>"btn btn-primary glyphicon glyphicon-remove", 
          :data=>{:confirm =>"Voce tem certeza?"}, 
          :method => :delete 
        %>
       
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

desafio/app/views/layouts/_colunaesquerda.html.erb
    <div class="well">
       <ul class="nav nav-pills nav-stacked">
        <li><h4>Clientes</h4></li>
          <li role="presentation"><%= link_to "Listar", root_path %></li>
          <li role="presentation"><%= link_to "Cadastrar", new_cliente_path %></li>
    </div>

desafio/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Projeto desenvolvido por <u>Bruno Marques de Andrade</u>
  </small>
</footer>

desafio/app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "Desafio Stefanini", root_path, :class=> "navbar-brand" %>
    </div>  
    <form accept-charset="UTF-8" action="/clientes/busca/" method="get" id="frmBusca" role="search" class="navbar-form navbar-right">
      <div class="form-group">
        <input type="text" placeholder="Nome do cliente" class="form-control" id="nome" name="nome">
      </div>
      <button class="btn btn-default" type="button" onclick="enviaBusca()">Buscar</button>
   </form>
  </div>
</nav>

desafio/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Prova Stefanini</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<!--
    <div class="alert alert-success" role="alert">
    <a href="#" class="alert-link">Cliente cadastrado com sucesso</a>
  </div>

  <div class="alert alert-danger" role="alert">
    <a href="#" class="alert-link">Houve algum erro no cadastro do cliente</a>
  </div>
-->


<div class="container">
  <div class="row">
    <%= render 'layouts/header' %>
  </div>
  <div class="row">
    <div class="col-xs-3">
      <%= render 'layouts/colunaesquerda' %>
    </div>
    <div class="col-xs-9">
      <div class="jumbotron">
        <%= yield %>
      </div>
    </div>
  </div>
  <div class="row">
    <%= render 'layouts/footer' %>
  </div>
</div>
<%= javascript_include_tag 'utils.bruno', 'data-turbolinks-track' => true %>
</body>
</html>